#ifndef __VERSION_H
#define __VERSION_H

/* Please do not modify this file manually 
   It's generated by version tool
*/

#define CQT_APP_VERSION "0.0.0.4"
#define CQT_APP_BUILD "1809301340"
#define CQT_RELEASE_DATE "30 Sep,2018"



#define FILEVER 	0,0,0,4
#define PRODUCTVER 	0,0,0,4
#define STRFILEVER 	"0, 0, 0, 4\0"
#define STRPRODUCTVER 	"0, 0, 0, 4\0"


#endif
